services:
  psql:
    image: postgres:16
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d inventory"]
      interval: 5s
      timeout: 5s
      retries: 5
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "4000:80"
    volumes:
      - ./inventory-service:/app
    networks:
      - inventory-network
    depends_on:
      psql:
        condition: service_healthy
    environment:
      - DB_HOST=psql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=inventory

volumes:
  pgdata:

networks:
  inventory-network:
  
  